stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-ct-scan-image

  prepare_base_model: 
    cmd: python src/cnn_classifier/pipeline/stage_02_prepare_base_mode_pipe.py
    deps: 
      - src/cnn_classifier/pipeline/stage_02_prepare_base_mode_pipe.py
      - config/conig.yaml
    params: 
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - LEARNING_RATE
      - WEIGHTS
    outs: 
      - artifacts/prepare_base_model
  training: 
    cmd: python src/cnn_classifier/pipeline/stage_03_model_training_pipe.py

    deps: 
      - src/cnn_classifier/pipeline/stage_03_model_training_pipe.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/prepare_base_model
    
    params: 
      - IMAGE_SIZE
      - AUGMENTATION
      - EPOCHS
      - BATCH_SIZE
    outs: 
      - artifacts/training/model.h5

  evaluation: 
    cmd: python src/cnn_classifier/pipeline/stage_04_model_evaluation_pipe.py

    deps: 
      - src/cnn_classifier/pipeline/stage_04_model_evaluation_pipe.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-ct-scan-image
      - artifacts/training/model.h5

    params: 
      - IMAGE_SIZE
      - BATCH_SIZE

    metrics: 
    - scores.json: 
        cache: false
